# Generated by Django 4.2.20 on 2025-04-09 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Qbox_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quations',
            new_name='Questions',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='quations',
            new_name='questions',
        ),
    ]
